const actions = {
	DISPLAY_ALERT: "DISPLAY_ALERT",
	CLEAR_ALERT: "CLEAR_ALERT",

	SETUP_USER_BEGIN: "SETUP_USER_BEGIN",
	SETUP_USER_SUCCESS: "SETUP_USER_SUCCESS",
	SETUP_USER_ERROR: "SETUP_USER_ERROR",
};

export default actions;
