const actions = {
	DISPLAY_ALERT: "DISPLAY_ALERT",
	CLEAR_ALERT: "CLEAR_ALERT",
	SETUP_USER_BEGIN: "SETUP_USER_BEGIN",
	SETUP_USER_SUCCESS: "SETUP_USER_SUCCESS",
	SETUP_USER_ERROR: "SETUP_USER_ERROR",
	TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
	LOGOUT_USER: "LOGOUT_USER",
	UPDATE_USER_BEGIN: "UPDATE_USER_BEGIN",
	UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
	UPDATE_USER_ERROR: "UPDATE_USER_ERROR",
};

export default actions;
